### ISSUE TITLE
iOS app after path crashes on start

### ISSUE THREAD

**Issue by dinhthiet2702** [Impact-I/reFlutter#206] opened 2022-09-02 17:33 UTC
Hi I am using refutter 0.7.2 after the app path crashes on startup, if not using refutter the app still works fine. thank you for your help
link ipa: https://drive.google.com/drive/folders/1oMEKA5pDJU02T4C-x41CL6zpCqy_vKhh
<img width="570" alt="Screen Shot 2022-09-03 at 12 28 48 am" src="https://user-images.githubusercontent.com/58399579/188207142-687f00ef-00d9-491c-9762-3c9017264edb.png">

**Comment by Impact-I** [comment] 2022-09-03 18:02
Duplicate of #203

**Closed as completed by Impact-I** 2022-09-03 18:02 UTC
